// CREATE TABLE IF NOT EXISTS `post` (
//   id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
//   date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
//   title varchar(100) NOT NULL,
//   content TEXT
// ) ENGINE=InnoDB DEFAULT CHARSET=utf8;